apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sanjay968673064/grafana-gitops.git  # <-- change this
    targetRevision: HEAD
    path: grafana

  destination:
    server: https://kubernetes.default.svc
    namespace: grafana

  syncPolicy:
    automated:
      prune: true        # delete resources removed from Git
      selfHeal: true     # auto-fix if someone manually changes things
    syncOptions:
      - CreateNamespace=true